codedge-llc/pigeon

lib/pigeon/gcm.ex, test/gcm_test.exs
The GCM notifications can now be configured on an ad-hoc basis by
passing a map as the second argument. If the second argument is not
specified then the value from the config will be used.
This allows multiple tokens to be used. For example you support multiple Android apps from the same server. Or if you are using a separate GCM token for Android and Web.
=> feat: allow per-push config for GCM

lib/pigeon/apns_worker.ex, lib/pigeon/notification.ex
From the developer docs[1]:
> If you omit this header and your APNs certificate does not specify
> multiple topics, the APNs server uses the certificate’s Subject as
> the default topic.
[1] https://goo.gl/v3nJZm
=> feat: make apn topic optional

lib/pigeon/notification.ex, test/apns_notification_test.exs
This PR adds a function so that the user can add a `mutable-content` flag to the `aps` dictionary, which indicates iOS 10 that there's content to be fetched to show within the notification using Service Extension.
=> Adds a function to add the mutable-content flag to APNs, for notification content preview on iOS 10

.travis.yml
build matrix based on Phoenix: https://github.com/phoenixframework/phoenix/blob/master/.travis.yml
~~I'm seeing some strange behaviour with Pigeon, and trying to determine if upgrading to Erlang 19 is the reason.~~ (update: my strange issue was due to mocking things wrong)
Also, it couldn't hurt to be testing both versions of OTP.
=> travis: run tests on Erlang 18.3 and Erlang 19

mix.exs
Otherwise Pigeon will not start for Erlang VM releases
=> Add kadabra to applications

docs/APNS Apple iOS.md
According to https://github.com/codedge-llc/pigeon/blob/5cad838126aa8331a7f48256d06c308a957513c0/lib/pigeon/apns.ex#L36
=> Rename 'to' → 'name' in docs for APNS custom workers

README.md, docs/APNS Apple iOS.md, docs/Getting Started.md, lib/pigeon/adm_worker.ex, lib/pigeon/apns.ex, lib/pigeon/gcm.ex, lib/pigeon/notification.ex, test/adm_notification_test.exs, test/apns_test.exs, test/gcm_test.exs
Still WIP
@talklittle I'm guessing I got the ADM.Notification docs correct. I noticed in my doctests that ADM's `new/2` fails when data is `nil`. I don't know if there is a reason you would ever send a push without a data payload, but it should either be fixed or made non-optional.
=> docs: docs for v1.0

lib/pigeon/apns.ex, lib/pigeon/apns_config.ex, lib/pigeon/apns_worker.ex, lib/pigeon/http2_client/kadabra.ex, test/apns_test.exs
Can now be configured on a per-worker basis. Time specified in ms. Defaults to 10 minutes. @asgoel 
```elixir
config :pigeon, :apns,
default: %{
cert: "cert.pem",
key: "key_unencrypted.pem",
mode: :dev,
ping_period: 300_000
}
{:ok, pid} = Pigeon.APNS.start_connection(ping_period: 300_000)
```
=> feat: configurable ping period (closes #60)

lib/pigeon.ex, lib/pigeon/adm_worker.ex, lib/pigeon/apns.ex, lib/pigeon/gcm.ex, lib/pigeon/gcm_worker.ex, lib/pigeon/notification.ex, test/adm_notification_test.exs, test/gcm_test.exs, test/gcm_worker_test.exs
Hi,
This is the initial proposal for supporting HTTP2 in FCM. I do not expect this PR to be perfect and mergeable; I have some questions ;)
There are some breaking changes to parameters passed to on_response :
- it is now passed more values : 
`{:ok, [{:ok, id, regid}, {:retry, regid}, {:update, id, regid, newregid}]}`
It does not return the notification anymore. Usually the notification being send is available in the same scope the on_response handler is being sent. 
The `id` is the message id. I'm not sure we should return it. Is it useful? Given it also makes us handle more tuple arrities, I'm not sure it's a win.
Tell me what you think.
=> HTTP2 support for FCM

lib/pigeon/apns_config.ex, lib/pigeon/apns_worker.ex, test/apns_worker_test.exs
This comes from a real-world use case of ours where we have implemented our own retry mechanism with a back-off feature. One of the certs was invalid causing an endless loop of:
> 13:45:09.064 [error] Got GOAWAY, NO_ERROR, Last Stream: 0, Rest: {"reason":"BadCertificateEnvironment"}
Although Kadabra supports reconnects, there doesn't seem to be a way to disable it from within Pigeon.
=> feat: allow reconnect to be configured

lib/pigeon/fcm/worker.ex, mix.exs, test/fcm/worker_test.exs
Reconnects FCM socket only on subsequent pushes after a disconnect. Prevents infinite reconnect loop.
=> fix: GOAWAY session_timed_out (closes #81)

lib/pigeon/apns/config.ex, lib/pigeon/fcm.ex, lib/pigeon/fcm/worker.ex, lib/pigeon/http2_client/kadabra.ex, lib/pigeon/http2_stream.ex, mix.exs, test/fcm_test.exs
FCM Issues Fixed:
- Sending too many pushes at once (now obeys `max_concurrent_streams`)
- Sending a lot of RegID's in one notification (proper `DATA` frame chunking)
- Synchronous response waiting for multiple `FCM.Notification` structs
Note:
Sending a huge batch of synchronous pushes may take longer than the timeout (15secs). Passing an `:on_response` callback is recommended.
=> fix: proper handling of large FCM push batches

CHANGELOG.md, lib/pigeon/adm.ex, lib/pigeon/fcm/worker.ex, mix.exs, mix.lock
FCM servers throw ENHANCE_YOUR_CALM for pings and close active connections after a
brief period of time. Pinging is not really necessary, though the config
option left in so as not to break API.
=> fix: disabled pings for FCM.Worker

.travis.yml, CHANGELOG.md, docs/APNS Apple iOS.md, docs/Getting Started.md, mix.exs, mix.lock
Closes #107
Also:
- Added elixir 1.6 to travis config
- Removed outdated `use_2197: true` from APNS docs
=> fix: relax httpoison dependency to 0.x or 1.0

docs/APNS Apple iOS.md
If the PEM pass phrase is less than 4 characters it fails and there are no good error messages, google searches, or stack overflow posts to help you understand why it's failing. I added text to warn the reader of this.
I also changed the wording from "password" to "pass phrase" because that is the word used by the openssl script in the terminal. This help distinguish from the password that can, but not must be set when exporting the certificate or passkey.
=> Clarification to keep key conversion from failing

lib/pigeon/adm/result_parser.ex, test/adm/result_parser_test.exs
avoid crash at `String.to_existing_atom/1`
=> ADM: enumerate known error values

lib/pigeon/apns/notification.ex
Functions `put_alert` and `new` now can accept `map` type for the second and first arguments accordingly.
=> Allow to pass maps in functions typespecs

lib/pigeon/adm/worker.ex, lib/pigeon/fcm/notification.ex, test/apns_test.exs
FCM Specifies 3 keys that were missing in this package:
* `content_available`
* `mutable_content`
* `condition`
This PR aims to correct the missing keys and also moves the FCM documentation inline into this package.
=> Add Missing Keys for FCM notifications

lib/pigeon/apns/notification.ex, lib/pigeon/apns/shared.ex, test/apns_test.exs
The `apns-priority` header field is currently unsupported.  Add `priority` as an element in the `Notification` struct, and include in the headers sent to the apns service.
=> Added priority to notifications

lib/pigeon/fcm.ex
Formatting was off by two spaces, this will make the entire handler func be in the code block.
=> Fix spacing so function doc formats correctly

mix.exs
Joken 2.1 was released and it is a minor update only because we removed the unnecessary application startup.
https://github.com/joken-elixir/joken/releases/tag/v2.1.0
It also clean ups some warnings so I thought it would be good to update here too to avoid having to override it. I've also used the minor version only here to avoid locking possible patch updates.
=> chore: update Joken

lib/pigeon/apns/notification.ex, lib/pigeon/apns/shared.ex
According to the [Apple documentation](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns?language=objc) the new `apns-push-type` header is required for sending notifications to iOS 13 (and ignored by earlier versions).
This change adds a field to the `APNS.Notification` struct and sets the header when sending the notification.
=> Add apns-push-type header for iOS 13

mix.exs
Just a tiny change to allow use of Poison 4.0 without an override.
=> Allow Poison 4.0

lib/pigeon/apns/error.ex
Encountered this error and got back an `:unknown_error` from Pigeon. After some debugging found out that this error was missing from the list.
Verified all errors are implemented from this list: https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/handling_notification_responses_from_apns
PS. thanks for this wonderful library!
=> Add APNS InvalidPushType error

lib/pigeon/fcm/config.ex
Our application calls `Pigeon.FCM.push/1` roughly like so:
```elixir
"/some/topic/name"
|> Pigeon.FCM.Notification.new(params, data)
|> Pigeon.FCM.Notification.put_content_available(true)
|> Pigeon.FCM.push()
```
but we get the following error:
```sh
[error] GenServer #PID<0.3526.0> terminating
** (FunctionClauseError) no function clause matching in Pigeon.Configurable.Pigeon.FCM.Config.parse_result/4
(pigeon 1.5.0) lib/pigeon/fcm/config.ex:170: Pigeon.Configurable.Pigeon.FCM.Config.parse_result("/some/topic", %{"message_id" => <scrubbed-message-id>}, #Function<4.94564371/1 in Pigeon.FCM.sync_push/2>, %Pigeon.FCM.Notification{collapse_key: nil, condition: nil, content_available: false, dry_run: false, message_id: nil, mutable_content: false, payload: %{"data" => %{<scrubbed-data>, …
```
=> Add case to handle single result

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/workflows/ci.yml, .gitignore, .prettierignore, README.md, config/test.exs, docs/ADM Amazon Android.md, docs/APNS Apple iOS.md, docs/FCM Android.md, docs/Migrating to v1-1-0.md, lib/pigeon/adm/notification.ex, lib/pigeon/fcm.ex
Adds new CI jobs:
- Prettier - checks formatting on all JSON, YAML and Markdown files.
- Format/Credo - runs `mix format --check-formatted` and `mix credo`.
Also: cleaned up files to pass new CI jobs.
=> ci: add prettier and check jobs

lib/pigeon/apns/jwt_config.ex, lib/pigeon/apns/token.ex
This ensures the token is only generated once and used across all workers
This fixes #226
=> Move token generation into Pigeon.APNS.Token

lib/pigeon/apns/jwt_config.ex
We noticed there was an issue where fetching tokens for our development pushes were causing some conflicts with our pushes to release devices. This is a simple fix to ensure that the token generated for `:dev` or `:prod` have their own unique token lifecycle, since apple is finicky about how many times you request a token. It has been a bit since we made this fix but never got around to upstreaming it, so I forget the details on _what_ error we were seeing a lot of.
=> fix: use uri to make token storage key unique

mix.exs
It appears that Mix only looks at the first two conditions here:
```elixir
{:httpoison, "~> 0.7 or ~> 1.0 or ~> 2.0"},
```
so it ends up failing for `httpoison` versions >= 2.0 when other deps require it:
```bash
> mix deps.get
Resolving Hex dependencies...
Resolution completed in 0.121s
Because openai >= 0.4.2 depends on httpoison ~> 2.0 and pigeon >= 1.1.5 depends on httpoison ~> 0.7 or ~> 1.0, openai >= 0.4.2 is incompatible with pigeon >= 1.1.5.
And because your app depends on openai ~> 0.5.3, pigeon >= 1.1.5 is forbidden.
So, because your app depends on pigeon ~> 2.0.0-rc.1, version solving failed.
```
=> Fix Mix Deps Version Conflicts (Remove Match on `~> 0.7` for `httpoison`

CHANGELOG.md, mix.exs
This is a small update to the 1.6 branch.
I'm not quite ready to jump to the 2.x rc.
=> Relax Poison dependency to allow 5.x

lib/pigeon/application.ex
This was fixed in the 1.6 branch, but not in master.
Fixes the warning
```
warning: using map.field notation (without parentheses) to invoke function Pigeon.Http2.Client.Kadabra.start() is deprecated, you must add parentheses instead: remote.function()
Warning:   (pigeon 1.6.2) lib/pigeon.ex:16: Pigeon.start/2
```
=> Fix Elixir 1.17 deprecation

lib/pigeon/legacy_fcm/config.ex
Fix for #265
Adds an "unknown" response if the response error is nil
=> Macro.underscore - no match of right hand side value: nil

CHANGELOG.md, lib/pigeon/adapter.ex, lib/pigeon/dispatcher_worker.ex
As pointed out in the #203 ([comment](https://github.com/codedge-llc/pigeon/issues/203#issuecomment-2186245808)), the `{:stop, reason}` clause is missing, which leads to `CaseClauseError`s instead of proper error handling.
I also moved the `handle_info` callback below `handle_push` as it mentions "all other messages", which logically should be a follow-up to what handle_push` has in its doc.
As a side note,  I couldn't find a case in which `{:stop, reason, new_state}` for `handle_info` is invoked, but I didn't want to accidentally break anything, so I left it as it was :)
=> fix: DispatchWorker missing a 2-element stop clause in handle_info

config/test.exs, lib/pigeon/dispatcher.ex, lib/pigeon/fcm.ex, lib/pigeon/fcm/config.ex, mix.exs, test/pigeon/fcm_test.exs, test/support/fcm.ex, test/test_helper.exs
closes #232
Updates the `Pigeon.FCM` and `Pigeon.FCM.Config` implementations to delegate the token refresh logic to `Goth`, as Goth v1.3+ now handles that directly
=> feat: support for Goth modules for FCM

lib/pigeon/apns/config_parser.ex
The following warning triggers on Elixir 1.18:
```
Compiling 1 file (.ex)
warning: :error.new/1 is undefined (module :error is not available or is yet to be defined)
│
33 │         type.new(opts)
│              ~
│
└─ lib/pigeon/apns/config_parser.ex:33:14: Pigeon.APNS.ConfigParser.parse/1
```
The solution was suggested here: https://github.com/elixir-lang/elixir/issues/14043
=> Fix compilation warning for Elixir 1.18

CHANGELOG.md
Cleaning up CHANGELOG across major versions.
=> docs: refactor CHANGELOG v1.6

lib/pigeon/apns/notification.ex
Just noticed this in the docs. Looks like it's a left-over from pre 2.x.
=> Fix incorrect doc string in Pigeon.APNS.Notification
